function on_click_sqltbl_upd_art_inreg(rowId) {

    var sqltbl_art_inreg_denum = 'sqlttbl_art_inreg';

    // Copiere date existente in sql table imp stocuri on click
    var value;
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'ID_ARTICOL');
    jr_set_value('txt_id_art', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'DENUMIRE');
    jr_set_value('txt_denumire', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'COD_ART_0');
    jr_set_value('txt_cod_art', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'COD_BARE');
    jr_set_value('txt_cod_bare', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'FURNIZOR_1');
    jr_set_value('txt_furnizor1', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'FURNIZOR_2');
    jr_set_value('txt_furnizor2', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'STOC');
    jr_set_value('txt_stoc', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'UM');
    jr_set_value('txt_um', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'PER_VALAB');
    jr_set_value('txt_perioada_de_valab', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'DENSITATE');
    jr_set_value('txt_densitate', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'VOLUM');
    jr_set_value('txt_volum', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'BAXUIRE');
    jr_set_value('txt_baxuire', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'GREUTATE');
    jr_set_value('txt_greutate', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'PALETIZARE');
    jr_set_value('txt_paletizare', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'DIMENSIUNI_LXH');
    jr_set_value('txt_dimensiuni_lxh', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'LUNGIME');
    jr_set_value('txt_lungime', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'LATIME');
    jr_set_value('txt_latime', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'INALTIME');
    jr_set_value('txt_inaltime', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'DIAMETRU');
    jr_set_value('txt_diametru', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'STATUS');
    jr_set_value('lst_status', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'TIP_ARTICOL');
    jr_set_value('sqllst_tip_articol', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'ALT_TIP_ART');
    jr_set_value('txt_alt_tip_art', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'CATEGORIE');
    jr_set_value('sqllst_categorie', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'ALT_CATEGORIE');
    jr_set_value('txt_alt_categorie', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'SUBCATEGORIE');
    jr_set_value('sqllst_subcategorie', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'ALT_SUBCATEG');
    jr_set_value('txt_alt_subcateg', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'COD_ART_1');
    jr_set_value('txt_cod_art_0', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'COD_ART_2');
    jr_set_value('txt_cod_art_1', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'COD_ART_3');
    jr_set_value('txt_cod_art_2', value);
    value = jr_get_table_value(sqltbl_art_inreg_denum, rowId, 'COD_ART_4');
    jr_set_value('txt_cod_art_3', value);
    jr_show('txt_alt_tip_art');
    jr_show('txt_alt_categorie');
    jr_show('txt_alt_subcateg');
}