SELECT COD_ART_0, COD_ART_1, COD_ART_2, COD_ART_3, COD_ART_4, COD_ART_CORESP
FROM `_71RESIDENT`.IEMPC_ST_CNT_20L_PRV
WHERE step_id = (SELECT MAX(step_id) FROM `_71RESIDENT`.NP_NERA WHERE step = 1230 AND status = 0);
